In [1]:
import numpy as np

# 1. Create ndarrays

In [2]:
data1 = [1,2,3,4]

arr1 = np.array(data1)

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
data2 = [[1,2,3],[2,3,4]]
arr2 = np.array(data2)

In [5]:
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [6]:
arr2.shape

(2, 3)

In [7]:
arr2.ndim

2

## 1.1 dtypes

In [8]:
arr1 = np.array(data1, dtype=np.int32)

In [9]:
arr1.astype(np.float64) # new object

array([ 1.,  2.,  3.,  4.])

In [10]:
arr1[::2]

array([1, 3], dtype=int32)

## 1.2 Boolean Index

In [11]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [12]:
names == 'Bob'
data[names == 'Bob', :2]

array([[ 0.93968015, -0.2658421 ],
       [-0.82412966,  0.78099602]])

In [13]:
cond = names == 'Bob'
data[~cond]

array([[ 0.06390406,  0.76194522,  0.00902223,  0.13296652],
       [-0.02845863,  1.8685588 ,  0.4287105 ,  0.1405375 ],
       [ 1.10148708,  0.15419454, -1.5261909 , -0.1135067 ],
       [ 0.2875502 , -1.5207574 , -0.03422493, -1.05150693],
       [-1.7028151 ,  0.74914732, -1.54277463, -2.15713964]])

In [14]:
# boolean operation
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[ 0.93968015, -0.2658421 , -0.09633515,  1.69684164],
       [-0.02845863,  1.8685588 ,  0.4287105 ,  0.1405375 ],
       [-0.82412966,  0.78099602,  0.51451238,  0.57379638],
       [ 1.10148708,  0.15419454, -1.5261909 , -0.1135067 ]])

In [15]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points

xs, ys = np.meshgrid(points, points)

In [16]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

## conditions

In [17]:
data

array([[ 0.93968015, -0.2658421 , -0.09633515,  1.69684164],
       [ 0.06390406,  0.76194522,  0.00902223,  0.13296652],
       [-0.02845863,  1.8685588 ,  0.4287105 ,  0.1405375 ],
       [-0.82412966,  0.78099602,  0.51451238,  0.57379638],
       [ 1.10148708,  0.15419454, -1.5261909 , -0.1135067 ],
       [ 0.2875502 , -1.5207574 , -0.03422493, -1.05150693],
       [-1.7028151 ,  0.74914732, -1.54277463, -2.15713964]])

In [19]:
data1 = np.random.randn(7, 4)
data1

array([[-1.60428679,  0.77269524, -0.6964432 ,  0.52175193],
       [-0.12265747,  1.41509407,  1.27882655,  0.11609146],
       [-0.45574003, -1.45886215,  0.93554617,  0.71086704],
       [-0.80400829, -0.9968307 ,  1.52334195,  0.0140811 ],
       [ 0.32598624,  0.71583028,  0.2686089 , -0.82521743],
       [ 1.18506487, -0.077776  , -1.27119828, -0.56364634],
       [ 1.63179278,  1.02395732, -0.41848609,  0.74829595]])

In [20]:
cond = [True, False, False, True]

In [21]:
np.where(cond, data, data1)

array([[ 0.93968015,  0.77269524, -0.6964432 ,  1.69684164],
       [ 0.06390406,  1.41509407,  1.27882655,  0.13296652],
       [-0.02845863, -1.45886215,  0.93554617,  0.1405375 ],
       [-0.82412966, -0.9968307 ,  1.52334195,  0.57379638],
       [ 1.10148708,  0.71583028,  0.2686089 , -0.1135067 ],
       [ 0.2875502 , -0.077776  , -1.27119828, -1.05150693],
       [-1.7028151 ,  1.02395732, -0.41848609, -2.15713964]])

In [22]:
np.where(cond, 0, data)

array([[ 0.        , -0.2658421 , -0.09633515,  0.        ],
       [ 0.        ,  0.76194522,  0.00902223,  0.        ],
       [ 0.        ,  1.8685588 ,  0.4287105 ,  0.        ],
       [ 0.        ,  0.78099602,  0.51451238,  0.        ],
       [ 0.        ,  0.15419454, -1.5261909 ,  0.        ],
       [ 0.        , -1.5207574 , -0.03422493,  0.        ],
       [ 0.        ,  0.74914732, -1.54277463,  0.        ]])

In [30]:
data1.argmax(axis=0)

array([6, 1, 3, 6])

## Boolean value calculation

In [32]:
(data1>0).sum()

16